/*******************************************************************
* (c) Copyright 2011-2012 Discretix Technologies Ltd.              *
* This file is licensed under the terms provided in the file       *
* libcc54/LICENSE in this directory or a parent directory          *
********************************************************************/

#ifndef _CRYS_PKA_DEFS_H_
#define _CRYS_PKA_DEFS_H_


#define CRYS_PKA_BARRETT_MOD_TAG_BUFF_SIZE_IN_WORDS 5

/*The size CRYS_PKA_RSA_HASH_CTX_SIZE_IN_WORDS should ALWAYS be >= CRYS_HASH_USER_CTX_SIZE_IN_WORDS (with the value of the SEP side)*/
#define CRYS_PKA_RSA_HASH_CTX_SIZE_IN_WORDS 33

/* size of buffer for Barrett modulus tag NP, used in PKI algorithms */
#define CRYS_PKA_ECPKI_BARRETT_MOD_TAG_BUFF_SIZE_IN_WORDS  CRYS_PKA_BARRETT_MOD_TAG_BUFF_SIZE_IN_WORDS

#define CRYS_PKA_MAXIMUM_MOD_BUFFER_SIZE_IN_WORDS CRYS_RSA_MAXIMUM_MOD_BUFFER_SIZE_IN_WORDS

#define CRYS_PKA_DOMAIN_BUFF_SIZE_IN_WORDS 2*CRYS_PKA_BARRETT_MOD_TAG_BUFF_SIZE_IN_WORDS

#define CRYS_PKA_PUB_KEY_BUFF_SIZE_IN_WORDS 2*CRYS_PKA_BARRETT_MOD_TAG_BUFF_SIZE_IN_WORDS

#define CRYS_PKA_PRIV_KEY_BUFF_SIZE_IN_WORDS 2*CRYS_PKA_BARRETT_MOD_TAG_BUFF_SIZE_IN_WORDS

#define CRYS_PKA_KGDATA_BUFF_SIZE_IN_WORDS   2*CRYS_PKA_MAXIMUM_MOD_BUFFER_SIZE_IN_WORDS

#define CRYS_PKA_ECDH_BUFF_MAX_LENGTH_IN_WORDS 1

#define CRYS_PKA_RSA_PRIME_INT_BUFF_SIZE_IN_WORDS 1

#define CRYS_PKA_CONV_KEY_CRT_BUFF_SIZE_IN_WORDS 1

#define CRYS_PKA_ECPKI_TMP_BUFF_MAX_LENGTH_IN_WORDS 1

#define CRYS_PKA_RND_ENTR_ESTIM_BUFF_MAX_LENGTH_IN_WORDS 514


/*! The valid maximum EC modulus size in 32-bit words */
#define CRYS_PKA_ECPKI_MODUL_MAX_LENGTH_IN_WORDS  18 /*(CRYS_ECPKI_MODUL_MAX_LENGTH_IN_BITS + 31)/(sizeof(DxUint32_t))*/

#define CRYS_PKA_KG_BUFF_MAX_LENGTH_IN_WORDS (CRYS_PKA_ECPKI_MODUL_MAX_LENGTH_IN_WORDS+1)

#define CRYS_PKA_EL_GAMAL_BUFF_MAX_LENGTH_IN_WORDS (4*CRYS_PKA_ECPKI_MODUL_MAX_LENGTH_IN_WORDS+4)

#define CRYS_PKA_ECDSA_SIGNE_BUFF_MAX_LENGTH_IN_WORDS (45*CRYS_PKA_ECPKI_MODUL_MAX_LENGTH_IN_WORDS+11)

#define CRYS_PKA_ECDSA_VERIFY_BUFF_MAX_LENGTH_IN_WORDS (45*CRYS_PKA_ECPKI_MODUL_MAX_LENGTH_IN_WORDS+11)





#endif /*_CRYS_PKA_DEFS_H_*/
